// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_encrypt
RawVector rcpp_encrypt(CharacterVector key, RawVector text);
RcppExport SEXP KMS2_rcpp_encrypt(SEXP keySEXP, SEXP textSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type key(keySEXP);
    Rcpp::traits::input_parameter< RawVector >::type text(textSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_encrypt(key, text));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_decrypt
RawVector rcpp_decrypt(RawVector text);
RcppExport SEXP KMS2_rcpp_decrypt(SEXP textSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type text(textSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_decrypt(text));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_generate
Rcpp::List rcpp_generate(CharacterVector key, int bytes);
RcppExport SEXP KMS2_rcpp_generate(SEXP keySEXP, SEXP bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type key(keySEXP);
    Rcpp::traits::input_parameter< int >::type bytes(bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_generate(key, bytes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"KMS2_rcpp_encrypt", (DL_FUNC) &KMS2_rcpp_encrypt, 2},
    {"KMS2_rcpp_decrypt", (DL_FUNC) &KMS2_rcpp_decrypt, 1},
    {"KMS2_rcpp_generate", (DL_FUNC) &KMS2_rcpp_generate, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_KMS2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
