# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_encrypt <- function(key, text) {
    .Call(KMS2_rcpp_encrypt, key, text)
}

rcpp_decrypt <- function(text) {
    .Call(KMS2_rcpp_decrypt, text)
}

rcpp_generate <- function(key, bytes) {
    .Call(KMS2_rcpp_generate, key, bytes)
}

